config/routes.rb
ShopApp::Application.routes.draw do
  devise_for :admins

  resources :admin_panel
  resources :products
  resources :orders
  
  match ':controller(/:action)' 
  match ':controller(/:action(/:id))'
  
  resources :store
  root :to => "store#index"
  
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :cart_items
  belongs_to :order
  
  def add_product(product)
    
    @current_item = CartItem.new(:product_id => product.id, :product_title => product.title, :product_price => product.price, :quantity => 1)

  end

end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  belongs_to :cart
  
  
  def increment_quantity
    self.quantity+=1
  end
  
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_one :cart
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :cart_item
end

app/controllers/admin_panel_controller.rb
class AdminPanelController < ApplicationController
  before_filter :authenticate_admin!
  def index
    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_filter :authenticate_admin!
  def index
    @orders = Order.all
  end
  
  def show
    @order = Order.find(params[:id])
    @cart = Cart.find_by_id(@order.cart_id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.xml
  before_filter :authenticate_admin!
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @products }
    end
  end

  # GET /products/1
  # GET /products/1.xml
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @product }
    end
  end

  # GET /products/new
  # GET /products/new.xml
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.xml
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to(@product, :notice => 'Product was successfully created.') }
        format.xml  { render :xml => @product, :status => :created, :location => @product }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.xml
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to(@product, :notice => 'Product was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.xml
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to(products_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
    @products = Product.all
  end
  
  def cart
    @cart = Cart.find_by_id(session[:cart_id])
  end

  def add_to_cart
    
    if session[:cart_id]
      @cart = Cart.find_by_id(session[:cart_id])
      product = Product.find(params[:id])
      @cart_item = @cart.cart_items.find_by_product_id(product.id)
      if @cart_item
        @cart_item.quantity+=1
        @cart_item.save
      else
        @cart_item = @cart.add_product(product)
        @cart.cart_items << @cart_item
       end
      redirect_to store_index_path
    else
      @cart = Cart.new
      @cart.save
      session[:cart_id] = @cart.id
      product = Product.find(params[:id])
      @cart_item = @cart.add_product(product)
      @cart_item.save
      @cart.cart_items << @cart_item
      redirect_to store_index_path
    end
  end
  
  def empty_cart
    @cart = Cart.find_by_id(session[:cart_id])
    @cart.cart_items.each do |item|
      item.destroy
    end
  
    redirect_to store_index_path
  end
  
  def checkout
    @cart = Cart.find_by_id(session[:cart_id])
    if @cart.cart_items.empty?
      redirect_to store_index_path
    else
      @order = Order.new
    end
  end
  
  def save_order
    @order = Order.new(params[:order]) 
    @order.cart_id =  session[:cart_id]
    if @order.save                     
      session[:cart_id] = nil
      redirect_to store_index_path
    else
      render :action => 'checkout'
    end
  end

end

app/helpers/admin_panel_helper.rb
module AdminPanelHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/admin_panel/index.html.erb
<h3>Admin panel</h3>

<%= link_to 'Products', products_path%><br>
<%= link_to 'Orders', orders_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShopApp</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
 <% if admin_signed_in? %>  
<%= link_to "Admin panel", admin_panel_index_path %> <%= link_to "Store", store_index_path %><br>
Hello, <%= current_admin.email %>! <%= link_to "Logout", destroy_admin_session_path %>  
<%end%>
<%= yield %>

</body>
</html>

app/views/orders/index.html.erb
<h3>Orders</h3>

<%@orders.each do |order|%>
Order id: <%= order.id%><br>
Customer name: <%= order.name%><br>
Cart id: <%= order.cart_id%>
<%= link_to 'Show details', order_path(order) %>
<br><br>
<%end%>

app/views/orders/show.html.erb
<h2>Order details</h2>
<table>
<tr>
	<td>
		<h3>Customer details</h3>
		<table border="2">
			<tr>
				<td>Name: </td>
				<td><%= @order.name%></td>
			</tr>
			<tr>
				<td>Post code: </td>
				<td><%= @order.post_code%></td>
			</tr>
			<tr>
				<td>City: </td>
				<td><%= @order.city%></td>
			</tr>
			<tr>
				<td>Street: </td>
				<td><%= @order.street%> <%= @order.h_number%></td>
			</tr>
			
		</table>
	</td>
</tr>
<tr>
	<td>
		<h3>Cart</h3>
		<table border="2">
			<tr>
				<th>Product</th>
				<th>Price</th>
				<th>Quantity</th>
			</tr>
    		<%@cart.cart_items.each do |item|%>
			<tr>
				<td><%=item.product_title%></td>
				<td>$<%=item.product_price%></td>
				<td><%=item.quantity%></td>
			</tr>
			<%end%>
		</table>
	</td>
</tr>

</table>
<br>
<%= link_to 'Back', orders_path%>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Price</th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.title %></td>
    <td><%= product.description %></td>
	<td>$<%= product.price %></td>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @product.title %>
</p>

<p>
  <b>Description:</b>
  <%= @product.description %>
</p>

<p>
  <b>Price:</b>
  $<%= @product.price %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/store/cart.html.erb
<h2>Your cart</h2>
<br>
<%if @cart && @cart.cart_items != []%>
<table border="2">
	<tr>
		<th>Product</th>
		<th>Price</th>
		<th>Quantity</th>
	</tr>
    <%@cart.cart_items.each do |item|%>
	<tr>
		<td><%=item.product_title%></td>
		<td>$<%=item.product_price%></td>
		<td><%=item.quantity%></td>
	</tr>
		
	<%end%>
</table>
<%= button_to "Checkout", :action => :checkout %>
<%= button_to "Empty Cart", :action => :empty_cart%>
<%else%>
Cart is empty
<%end%>
<br><br>
<%= link_to "Back", store_index_path %>

app/views/store/checkout.html.erb
<div>
  
  <% form_for :order, :url => { :action => :save_order } do |f| %>
    <fieldset>
      <legend>Please Enter Your Details</legend>

      <div>
        <%= f.label :name, "Name:" %>
        <%= f.text_field :name, :size => 40 %>
      </div>

      <div>
        <%= f.label :city, "City:" %>
        <%= f.text_field :city%>
      </div>
	  
	  <div>
        <%= f.label :street, "Street:" %>
        <%= f.text_field :street%>
      </div>
	  
	  <div>
        <%= f.label :h_number, "Home number:" %>
        <%= f.text_field :h_number%>
      </div>
	  
      <div>
        <%= f.label :post_code, "Post code:" %>
        <%= f.text_field :post_code%>
      </div>
    
      <%= submit_tag "Place Order", :class => "submit" %>
    </fieldset>
  <% end %>  
</div>

app/views/store/index.html.erb
<h1>Store</h1>
<%= link_to "Your cart", :action => :cart %>
<h2>Products</h2>
<table>
<%@products.each do |product|%>
<tr>
	<td>
		<h3><%=product.title%></h3>
		<%=product.description%><br>
		price: $<%= product.price%>
		<%= button_to "Add to Cart", :action => :add_to_cart, :id => product %>
	</td>
</tr>
<%end%>
</table>